### ISSUE TITLE
Warning: Selenium Standalone is not present.

### ISSUE THREAD

**Issue by kperwel** [seckardt/grunt-protractor-webdriver#15]
Hi,
This grunt-task looks perfect, but i have an problem.
When i'm running task with basic conf it shows:

```
#grunt protractor_webdriver
Running "protractor_webdriver:start" (protractor_webdriver) task
Starting Selenium server
Warning: Selenium Standalone is not present. Install with webdriver-manager update --standalone
 Use --force to continue.
Aborted due to warnings.
```

But i have Selenium Standalone installed. 

```
#webdriver-manager update --standalone
selenium standalone is up to date.
chromedriver is up to date.
```

Manual start works perfect:

```
#webdriver-manager start              
seleniumProcess.pid: 13180
11:23:13.973 INFO - Launching a standalone server
...
```

Any ideas how to solve it?

**Comment by marcelboettcher** [comment]
have exactly the same problem.

**Comment by SandroMartis** [comment]
Same here. Did i miss anything?

**Comment by eboukamza** [comment]
I have fixed this problem removing local install of protractor by rm `-rf node_modules/protractor` and installing protractor globally `npm install -g protractor`

**Comment by marlonpp** [comment]
+1

**Comment by marlonpp** [comment]
Found the "problem". 
You should update the webdriver-manager that is inside node_modules/protractor/bin/webdriver-manager

If you look at this project Gruntfile, you will find a shell command that do it:
node_modules/protractor/bin/webdriver-manager update --standalone --chrome

After this, it run perfectly.

**Comment by BrodaNoel** [comment]
Do it:
`where webdriver-manager`
This command will say you where is the webdriver-mamanger binary.
This is you webdriver "updated", but remember that grunt-protractor-webdriver is using the protractor/webdriver binary.
So, you should update using:
node_modules/protractor/bin/webdriver-manager update

**Comment by frankitoy** [comment]
+1

**Comment by donald-s** [comment]
+1

**Comment by MarkusPint** [comment]
How to fix this on Windows?

**Comment by LukasKraushofer** [comment]
for Windows use
node node_modules\protractor\bin\webdriver-manager update

**Comment by lsiden** [comment]
Just followed @marlonpp and @BrodaNoel's suggestions.

    $ node_modules/protractor/bin/webdriver-manager update --standalone --chrome
    selenium standalone is up to date.
    chromedriver is up to date.

Still getting:

    $ grunt myprotractor
    Running "protractor_webdriver:start" (protractor_webdriver) task
    Starting Selenium server
    Warning: Selenium Standalone is not present. Install with webdriver-manager update --standalone
     Use --force to continue.
