### ISSUE TITLE
grunt-protractor-webdriver blocks

### ISSUE THREAD

**Issue by MartinDelille** [seckardt/grunt-protractor-webdriver#19]
I have two setup with exactly the same configuration. On one, the grunt-protractor-webdriver task is blocking and on the other not.

Here are my output with the blocking one:

    $ grunt protractor-webdriver
    Running "protractor_webdriver:all" (protractor_webdriver) task
    Starting Selenium server

And with the other unblocking one:

    $ grunt protractor-webdriver
    Running "protractor_webdriver:all" (protractor_webdriver) task
    Starting Selenium server
    Shutting down Selenium server: http://127.0.0.1:4444
    
    Done, without errors.

What's wrong here?

**Comment by angelblade27** [comment]
The fix is actually checked in but we need to wait for the a new release https://github.com/seckardt/grunt-protractor-webdriver/issues/17#issuecomment-144934794

**Comment by angelblade27** [comment]
@seckardt  any eta when a new release will be pushed?

**Comment by MartinDelille** [comment]
I apply the patch and it worked! Waiting for the release.

**Comment by angelblade27** [comment]
So am I. @MartinDelille i'm new to this but curious how did you apply the patch? Create your own branch or in the node_modules/?

**Comment by MartinDelille** [comment]
I simply edit *node_modules/grunt-protractor-webdriver/tasks/protractor_webdriver.js* replacing manually line 23 by : 

    REGEXP_START_READY = /(Started org\.openqa\.jetty\.jetty\.Server)|(Selenium Server is up and running)/,
