### ISSUE TITLE
grunt Error: Cannot find module 'split'

### ISSUE THREAD

**Issue by bperkins06** [seckardt/grunt-protractor-webdriver#24]
'split' was removed from **package.json**, but **tasks/protractor_webdriver.js** still requires 'split'.
I had to include 'split' in my project's package.json to work around this issue.

grunt ERROR:
Loading "protractor_webdriver.js" tasks...ERROR
\>\> Error: Cannot find module 'split'

**Comment by seckardt** [comment]
Fixed with commit 3a05fa8b0a24efc4723d7f656cde536d5dd57c71
